### ISSUE TITLE
layer.open()问题

### ISSUE THREAD

**Issue by Qooence** [zuoyanart/vue-layer#10]
layer.open()怎么打开一个路径？

**Comment by kimihiro233** [comment]
用layer.iframe

**Comment by Qooence** [comment]
我需要打开一个外部链接,像‘http:www.baidu.com’,但是报错Cannot create property '_Ctor' on string 'http://www.baidu.com'

**Comment by kimihiro233** [comment]
写一个组件用来打开网页，然后用layer.iframe弹出这个组件

**Comment by zuoyanart** [comment]
是的， 暂不直接支持url类型的iframe
