### ISSUE TITLE
急急急 作者大大 目前如果弹框默认100%*100%的话  再点击会有问题 

### ISSUE THREAD

**Issue by 1973635434** [zuoyanart/vue-layer#102]
如果目前默认是100% * 100%的话 点击右上角全屏 再点击还原会出现原弹框大小发生改变 并且再次点击全屏 不起作用

**Comment by zuoyanart** [comment]
能否提供个demo, 让我重现

**Comment by 1973635434** [comment]
this.$layer.iframe({
      content: {
        content: z, 
        parent: that, 
        data: {} //props
      },
      area: [w, h],
      title: t,
      maxmin: true,
      resize: true,
      fixed: false,
      anim: 6,
    })

如果w 是100%  就会出现这个问题 
如果w 设置99.99%就不会出现这个问题

**Comment by zuoyanart** [comment]
我一会上线看看这个问题

**Comment by 1973635434** [comment]
好的  感谢

**Comment by zuoyanart** [comment]
@1973635434   最大化使用`layer.full(layerid);` 这个方法, area参数传一个正常尺寸的值即可, 目前还不支持百分比.
```js
//弹窗最大化
layer.full(layerid);
//弹窗最小化
layer.min(layerid);
//还原弹窗
layer.restore(layerid);
```

**Comment by 1973635434** [comment]
好的  感谢
