### ISSUE TITLE
希望新增使用插件对象，触发插件yes或者cancel回调

### ISSUE THREAD

**Issue by HU914** [zuoyanart/vue-layer#108]
运用场景：
1、使用iframe类的时候，content 为自定义组件，包括btn按钮，点击后，无法触发vue-layer的yes或者cancel回调，只能点击弹窗右上角的close按钮触发cacel回调，希望使用this.$layer插件对象，可以通过某一类方法，触发yes或者cancel回调，让父组件能够得到数据更新，或者得到通知，方便父组件做数据更新。例如：this.$layer.btn('yes',params),触发yes回调，yes为回调类型，yes回调或者cancel回调，params为回调参数。

**Comment by zuoyanart** [comment]
是在 `确定` 的时候要出发yes回调吗?

**Comment by HU914** [comment]
自定义确定按钮或者返回按钮，都希望存在可以回调的情况

**Comment by zuoyanart** [comment]
在弹窗组件里可以获取layerid, 这是不是你要的
```js
export default {
  data () {
    return {
      form: {
        name: '',
        region: '',
        date1: '',
        date2: '',
        delivery: false,
        type: [],
        resource: '',
        desc: ''
      }
    };
  },
  props: {
    layerid: {//自动注入的layerid
      type: String,
      default: ''
    },
    iframeData: {//传递的数据
      type: Object,
      default: () => {
        return {};
      }
    },
    lydata:{
      type: Object,
      default: () => {
        return {};
      }
    }
  },
  methods: {
    onSubmit () {
      //更新父对象数据信息
      this.$parent.$data.iframeData = Object.assign({}, this.form);
      //或者
      this.lydata.iframeData = Object.assign(this.lydata.iframeData, this.form);

      this.$layer.msg('成功');
      this.$layer.close(this.layerid);
    },
    quxiao () {
      this.$layer.close(this.layerid);
    }
  },
  watch: {
    iframeData: {
      handler: function () {
        this.form = this.iframeData;
      },
      deep: true,
      immediate: true
    }
  }
};
```
[http://layer.zuoyanit.com/](url)

**Comment by HU914** [comment]
这个layeriD 只能用来关闭弹窗，可以用来手动触犯回调吗？，比如我自定义了确定和返回按钮，我点击后，我该调用什么方法，触发layer外部的yes或者cancel。示例如下：

 this.$layer.iframe({
                    content: {
                        content: layer,
                        parent: this,
                        data:{}
                    },
                    shade: false,
                    maxmin: false,
                    area:['400px','auto'],
                    title: 'xxx',
yes：（）=> {},
                    cancel:()=>{}，

                })

**Comment by HU914** [comment]
我在layer组件内部自定义了确定和返回按钮，我如何触发上述this.$layer.ifarame中的yes或者cancel回调？

**Comment by zuoyanart** [comment]
这里有三种办法可以实现
* 传递function给iframe
* 子父传值调用
* 在ifrmae里定义prop的lyoption数据, 这个lyoption属性包含所有的配置项目(1.2.1新增)
