### ISSUE TITLE
layer.ifram data属性疑问

### ISSUE THREAD

**Issue by kimihiro233** [zuoyanart/vue-layer#11]
父组件中设置data:[]
子组件中设置props:['layerid']
没能取到layerid，自己设置参数也没能取到，是不是我写得不对？

**Comment by zuoyanart** [comment]
子组件代码： 
```js
  props: {
    layerid: {
      type: String,
      default: ''
    }
  },
```
这样写是可以获取到的，如果还获取不到，就贴下你的代码

**Comment by kimihiro233** [comment]
父组件：
`this.$layer.open({`
`  type: 2,`
`  icon: -1,`
`  content: {`
`    content: upload,`
`    parent: this,`
`    data: []`
`  },`
`  area: ['360px', '400px'],`
`title: "上传",`
`});`
子组件：
`export default {`
`  props: {`
`    layerid: {`
`      type: String,`
`      default: '',`
`    },`
`  },`
`  data: function () {`
`    console.log(this.layerid)`
`  },`
`}`

抱歉回复晚了，代码如上，layerid是空值

**Comment by zuoyanart** [comment]
data里为什么要调用props的属性呢？ 而且data应该是这样写的： 
```js
data() {
  return {}
}
```
正常使用props应该是在method， computed， mounted或者template里呀

**Comment by kimihiro233** [comment]
已解决，版本问题之前是0.8.5，一直用的npm update，没更新到新版本。。。。对不起！

**Comment by zuoyanart** [comment]
谢谢支持
