### ISSUE TITLE
多个IFRAME最小化BUG 🙉

### ISSUE THREAD

**Issue by pleaseyang** [zuoyanart/vue-layer#114]
多个IFRAME， 使用最小化BUG时候，不会像layer一样在最下角依次排列。而是覆盖到了一起。 @zuoyanart

**Comment by 1973635434** [comment]
@zuoyanart  作者大大 我也有这个问题 希望能尽快解决一下 感谢感谢

**Comment by zuoyanart** [comment]
这两天在赶 [sparender](https://github.com/zuoyanart/sparender) 这个开源工具,  我会尽快解决这个问题, 谢谢支持 @1973635434

**Comment by gjTool** [comment]
bug挺多的，作者一直没有修复，所以我去改了源码把bug都修复了，然后重新发布了一个npm包，名字是vl-layer

**Comment by zuoyanart** [comment]
bug已经修复， 请下载最新版本体验
