### ISSUE TITLE
layer.iframe transform 导致的模糊问题

### ISSUE THREAD

**Issue by zhangWeiZhuang** [zuoyanart/vue-layer#116]
![image](https://user-images.githubusercontent.com/44084004/103185105-eae51080-48f5-11eb-83ae-2aaba0c22e8a.png)
hi，大神
关于 layer.iframe 中 transform 导致 字体等一系列模糊的问题，能帮忙解决一下吗？

**Comment by zuoyanart** [comment]
现在还有这个问题吗？

**Comment by zhangWeiZhuang** [comment]
这个问题目前一直存在。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zuoyanart/vue-layer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午5:17
***@***.***&gt;;
抄送:&nbsp;"深情不及久伴 i ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zuoyanart/vue-layer] layer.iframe transform 导致的模糊问题 (#116)





 
现在还有这个问题吗？

**Comment by zuoyanart** [comment]
这个问题是高或宽是奇数导致的， 你可以先设置成偶数用着， 我来想办法

**Comment by zhangWeiZhuang** [comment]
好的，大哥！


感谢！！感谢！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zuoyanart/vue-layer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 下午5:31
***@***.***&gt;;
抄送:&nbsp;"深情不及久伴 i ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zuoyanart/vue-layer] layer.iframe transform 导致的模糊问题 (#116)





 
这个问题是高或宽是奇数导致的， 你可以先设置成偶数用着， 我来想办法

**Comment by zuoyanart** [comment]
增加了个方法，自动把数字转换为偶数，1px在视觉上误差可以认为忽略（目前先这样处理了， 稍后会发版本）
