### ISSUE TITLE
this.$layer.iframe设置全屏的时候内容高度没有设置全屏，导致上面滚动查看，下面有一部分的留白区域

### ISSUE THREAD

**Issue by chineseLon** [zuoyanart/vue-layer#118]
![image](https://user-images.githubusercontent.com/57129514/109244930-91785f80-781a-11eb-801a-f4ead9f512ef.png)

**Comment by gjTool** [comment]
bug挺多的，作者一直没有修复，所以我去改了源码把bug都修复了，然后重新发布了一个npm包，名字是vl-layer

**Comment by zuoyanart** [comment]
不好意思, 更新慢了, 这个问题已经修复, 加上其他问题修复完毕后, 就会发布更新版本

**Comment by zuoyanart** [comment]
版本已经发布
