### ISSUE TITLE
iframe层级

### ISSUE THREAD

**Issue by kimihiro233** [zuoyanart/vue-layer#13]
0.9.4中打开两个iframe，第二个会出现在第一个下方

**Comment by zuoyanart** [comment]
好的， 我会修复

**Comment by zuoyanart** [comment]
fixed version 0.9.5

**Comment by kimihiro233** [comment]
第二个iframe的遮罩没有罩住第一个iframe

**Comment by zuoyanart** [comment]
是什么浏览器？代码更新了吗？查看下iframe的z-index值

**Comment by kimihiro233** [comment]
第一个iframe的z-index: 55160432
第二个iframe的z-index: 55160478
遮罩都没有设置z-index,
代码是从git上dist里拉取的
浏览器是Firefox

**Comment by zuoyanart** [comment]
我用火狐测了一下，发现是正常的。 从z-index值上来看，也应该是正常的。你再测试下，不行就再提供下浏览器版本

**Comment by kimihiro233** [comment]
![image](https://user-images.githubusercontent.com/11582292/40647569-c12e8444-635e-11e8-8b5f-fe6bf19f4295.png)
标题1为一级弹窗，标题2为二级弹窗，2的大小比1小，且2的遮罩在1下面，所以2弹出的时候，点击1，1会遮住2

**Comment by dickwu** [comment]
https://github.com/zuoyanart/vue-layer/blob/9419f5615da2a5c244bc196a19fd40893a9dd220/src/css/index.less#L19

这里加一个!important就好了

**Comment by zuoyanart** [comment]
实测已经正常遮罩了
