### ISSUE TITLE
有哪些自带的 icon 

### ISSUE THREAD

**Issue by ZHangTong920919** [zuoyanart/vue-layer#14]
let id = self.$layer.msg(data.msg, {
              time: 10,
              icon: 1
           }, () => {
              self.$layer.close(id);
            });

icon 取值 1-5 均无变化

**Comment by zuoyanart** [comment]
暂时还没有此功能。可以考虑是否新增此功能

**Comment by zuoyanart** [comment]
增加了几个图标，可以测试看看
