### ISSUE TITLE
iframe层级

### ISSUE THREAD

**Issue by a1029382825** [zuoyanart/vue-layer#15]
当在iframe类型的弹窗elementui  form中的下拉菜单时，layer会遮挡elementui弹出的下拉选项

**Comment by zuoyanart** [comment]
好的， 会马上修复

**Comment by zuoyanart** [comment]
这个是因为element的下拉是注入到body里而不是iframe里，有点恶心。
我做的机制， 可以通过class重置iframe的z-index值， 最小500，低于element的2000就好

**Comment by a1029382825** [comment]
好的，感谢🙏
