### ISSUE TITLE
标题栏会突出弹出窗口

### ISSUE THREAD

**Issue by kimihiro233** [zuoyanart/vue-layer#2]
如图，
![snipaste_2018-02-07_08-48-05](https://user-images.githubusercontent.com/11582292/35892287-b0323dca-0be3-11e8-84b8-152e23d25963.jpg)
默认标题栏有15px在弹出窗口外面，是由下面的CSS引起
`h2.notice-title{padding-left: 15px;}`
我暂时用h2.notice-title{box-sizing: border-box}解决

**Comment by zuoyanart** [comment]
是不是css reset中没有定义全局box-sizing: border-box？我再强制定义一下

**Comment by kimihiro233** [comment]
确实是这样，后端写页面，没有考虑到这样做

**Comment by zuoyanart** [comment]
下个版本会修复，谢谢
