### ISSUE TITLE
confirm点击确定取消如何关闭弹层？

### ISSUE THREAD

**Issue by Kennersky** [zuoyanart/vue-layer#24]
![image](https://user-images.githubusercontent.com/2129521/40949142-330e6dc8-689f-11e8-8833-bbdf436d94ac.png)
写this.$layer.close()报错。
最后试了要先把this初始成_this后再调用
_this.$layer.closeAll(); 可以关闭。

**Comment by zuoyanart** [comment]
这个是因为this作用域的问题，用箭头函数可以正确指向this， 另外可以可以定id
`let id = this.$layer.confirm()`
然后 
`this.$layer.close(id)`
