### ISSUE TITLE
弹窗不能使用，vue报警告？

### ISSUE THREAD

**Issue by AiJiangnan** [zuoyanart/vue-layer#26]
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by zuoyanart** [comment]
`import vue from 'vue/dist/vue.js'`  请问你是这样引入vue的吗

**Comment by AiJiangnan** [comment]
谢谢，自己解决了，就是这样的，是Vue的版本导入问题
