### ISSUE TITLE
把弹出层最大化按钮加上呗

### ISSUE THREAD

**Issue by cilfm** [zuoyanart/vue-layer#27]
把弹出层最大化按钮加上呗

**Comment by sunweizhe** [comment]
同求

**Comment by jpz966906738** [comment]
同求最大最小化

**Comment by Zhangyue02** [comment]
现在有最小化，可是加上maxmin:true 没起到作用，应该怎么用呢？

**Comment by Zhangyue02** [comment]
<script src="../js/vue-layer.js"></script>
Vue.prototype.$layer = layer(Vue);
![image](https://user-images.githubusercontent.com/18166790/55206995-70b0c500-5213-11e9-8b4a-13fa4e885312.png)
这种引入的方式

**Comment by Zhangyue02** [comment]
dist 中 vue-layer.js不是最新的

**Comment by zuoyanart** [comment]
已经添加
