### ISSUE TITLE
install时报错怎么解决

### ISSUE THREAD

**Issue by gxlnm** [zuoyanart/vue-layer#29]
error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，

安装 .NET Fram ework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了 其他位置，请将其位置添加到系统 路径中。 [F:\coffee\nodejs\microblog\node_modules\mongodb\node_modules\kerberos
bui ld\binding.sln] MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，
安装 .NET Fram ework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了 其他位置，请将其位置添加到系统 路径中。 [F:\coffee\nodejs\microblog\node_modules\mongodb\node_modules\bson\buil d\b inding.sln] mongodb@1.3.23 node_modules\mongodb ├── bson@0.2.5 └── kerberos@0.0.3

**Comment by zuoyanart** [comment]
是这个项目吗？ package中并没有mongodb的引入啊

**Comment by zuoyanart** [comment]
windows因为没有c++编译器所有需要装vs，PS：真爱生命，远离windows

**Comment by zuoyanart** [comment]
你的系统是mongodb做数据库吗？

**Comment by gxlnm** [comment]
C:\Users\Admin\Desktop\work\jiji_digital\vue\node_modules\nodejieba>if not defin
ed npm_config_node_gyp (node "C:\Users\Admin\AppData\Roaming\npm\node_modules\np
m\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp.js" rebuild )  else (node "C:\Users\Admin\AppData\Roaming\npm\node_modules\n
pm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，
1) 安装 .NET Fram
ework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了
其他位置，请将其位置添加到系统
路径中。 [C:\Users\Admin\Desktop\work\jiji_digital\vue\node_modules\nodejieba\bu
ild
\binding.sln]


应该不是数据库的问题吧，问题上的是百度碰到的类似的报错，就粘过来，这个是我本机的报错，麻烦再看看，不好意思

**Comment by zuoyanart** [comment]
python2.7安装了吗

**Comment by gxlnm** [comment]
装了的
