### ISSUE TITLE
this.$layer.iframe 如何隐藏标题

### ISSUE THREAD

**Issue by ZHangTong920919** [zuoyanart/vue-layer#3]
![image](https://user-images.githubusercontent.com/20830048/35893814-bd5787d8-0bea-11e8-9762-ae11166f429a.png)

为了和界面风格统一，已经在 组件中添加了标题，如何再自带的title 给隐藏掉？

**Comment by zuoyanart** [comment]
你是说标题栏还是标题文字？

**Comment by ZHangTong920919** [comment]
整个 自带的标题栏

**Comment by ZHangTong920919** [comment]
![image](https://user-images.githubusercontent.com/20830048/36522095-73b86452-17d5-11e8-88eb-b241b28f203c.png)

如果所示添加了css 但是仍会显示
