### ISSUE TITLE
请问为什么用 vue-layer 以后图标没有了？

### ISSUE THREAD

**Issue by ddcatgg** [zuoyanart/vue-layer#31]
如题，代码如下：

	<script>
	import Vue from 'vue';
	import layer from 'vue-layer';

	Vue.prototype.$layer = layer(Vue);

	export default {
		data () {
			return {
			};
		},
		created () {
			this.$layer.alert('hello', {'icon': 3});
		}

	};
	</script>

弹出的提示框如下图：

![image1](https://user-images.githubusercontent.com/8475003/43504278-56a913f0-9595-11e8-95e8-7c75743311a6.png)

正常应该文字前有一个图标的。

**Comment by zuoyanart** [comment]
vue-layer本身就是不带图标的，这个功能我正在考虑是否加上去

**Comment by ddcatgg** [comment]
@zuoyanart 好的，非常感谢！初识 layer.js 就是惊艳于它的图标：）

**Comment by zuoyanart** [comment]
#14

**Comment by wanghai1989** [comment]
> vue-layer本身就是不带图标的，这个功能我正在考虑是否加上去

没有图标局限性太大了，提示分为正确提示跟错误提示。没有图标，只有文字体验很不好
