### ISSUE TITLE
iframe BUG

### ISSUE THREAD

**Issue by kunJuly** [zuoyanart/vue-layer#32]
layerOptions: {
          type: 2, //0（信息框，默认）1（页面层）2（iframe层）3（加载层）4（tips层）
          title: '信息',
          content: {
            content: IntelligentBlock,
            parent: vm,
            data: {}
          },
          area: ['300px', '300px'],
          offset: 'auto',
          icon: -1,
          btn: ['继续弹出', '全部关闭'], //只是为了演示
          time: 0,
          shade: false,//是否显示遮罩
          yes: '',
          cancel: '',
          // tips: [0,{}],//支持上右下左四个方向，通过1-4进行方向设定,可以设定tips: [1, '#c00']
          tipsMore: true,//是否允许多个tips
          shadeClose: false,//点击遮罩是否关闭
          zIndex: vm.$layer.zIndex
        }

options 代码如上
多开 iframe 层之后 移动 只能移动 最新打开的一层

**Comment by zuoyanart** [comment]
最近正在出差，会尽快看这个问题

**Comment by appmakerpeng** [comment]
move: false,好像没用，请修复下

**Comment by appmakerpeng** [comment]
move:false失效 ,请尽快修复

**Comment by appmakerpeng** [comment]
offset:'rb',也无效

**Comment by zuoyanart** [comment]
这个工具只是借鉴了layui的体验，源码实现完全不一致，一些参数也和layer不一致，我会在文档中注明，move参数和offet现在是不支持的。如果你特别需要，请说明下场景，我会尽快评估您的使用场景

**Comment by moquan0116** [comment]
`content: {
                    content: RecordInfo, // 传递的组件对象
                    parent: this, // 当前的vue对象
                    data: {
                        id: data.id, // 事务ID
                        test: [],
                        test2:{x:123}
                    }
                }`
![dsfsdfsdfsdfdsfdsfdsfdsfsdfdsfsdf](https://user-images.githubusercontent.com/23159073/46007055-9d144900-c0eb-11e8-9dba-b9d1057ddcbf.png)

**Comment by fengyanzhang** [comment]
> `content: { content: RecordInfo, // 传递的组件对象 parent: this, // 当前的vue对象 data: { id: data.id, // 事务ID test: [], test2:{x:123} } }`
> ![dsfsdfsdfsdfdsfdsfdsfdsfsdfdsfsdf](https://user-images.githubusercontent.com/23159073/46007055-9d144900-c0eb-11e8-9dba-b9d1057ddcbf.png)

请问你这个问题解决了吗？我也遇到这个问题了

**Comment by cuitwangshicheng** [comment]
> > `content: { content: RecordInfo, // 传递的组件对象 parent: this, // 当前的vue对象 data: { id: data.id, // 事务ID test: [], test2:{x:123} } }`
> > ![dsfsdfsdfsdfdsfdsfdsfdsfsdfdsfsdf](https://user-images.githubusercontent.com/23159073/46007055-9d144900-c0eb-11e8-9dba-b9d1057ddcbf.png)
> 
> 请问你这个问题解决了吗？我也遇到这个问题了

暂时用JSON.stringify转成字符串穿进去，再转回来
