### ISSUE TITLE
this.$layer.iframe 不能传函数?

### ISSUE THREAD

**Issue by Ycsm2015** [zuoyanart/vue-layer#34]
在组件里面接收到为undefined.
另外,回调应该要怎样写比较好

**Comment by zuoyanart** [comment]
能不能具体点呢

**Comment by Ycsm2015** [comment]
layer.iframe({
  content: {
    content: componentName, //传递的组件对象
    parent: this,//当前的vue对象
    data:{
/* 在这里定义一个函数 fn:function(){} */
}
  },.....
在传递的组件对象里面获取不到.prop特性已经声明过了

**Comment by zuoyanart** [comment]
问题已经重现， 请等待最近几天的更新
