### ISSUE TITLE
请问下一个版本什么时候发布

### ISSUE THREAD

**Issue by cuitwangshicheng** [zuoyanart/vue-layer#37]
你好，我想请问你的下一个版本什么时候推出？现在这个功能确实有点太少。像最大最小化、事件回调等等会加入到下个版本吗？

**Comment by dickwu** [comment]
@zuoyanart 大大最近有空更新这个吗

**Comment by cuitwangshicheng** [comment]
> @zuoyanart 大大最近有空更新这个吗

从代码提交来看，是更新了的

**Comment by zuoyanart** [comment]
已经更新版本了。如果有bug，提交issues即可
