### ISSUE TITLE
ReferenceError: deepClone is not defined

### ISSUE THREAD

**Issue by fengyanzhang** [zuoyanart/vue-layer#38]
the.$layer.iframe({
          content: {
            content: HcDetail, //传递的组件对象
            parent: the,//当前的vue对象
            data:{
              tcData : {ID : glingData.ywzj}
            }//props
          },
          area:['800px','600px'],
          title: 'title'
        });

**Comment by cuitwangshicheng** [comment]
这个地方有个bug，不要用对象，把对象转成字符串传进去，再转一次。目前就这个问题，后面修复了估计就不会有这个问题了

**Comment by dickwu** [comment]
> 这个地方有个bug，不要用对象，把对象转成字符串传进去，再转一次。目前就这个问题，后面修复了估计就不会有这个问题了

能写一个例子吗

**Comment by cuitwangshicheng** [comment]
const layerId = this.$layer.iframe({
        content: {
          content: HdRealTimeIndexNew,
          parent: this.$parent,
          data: {data: JSON.stringify(stationInfo)}
        },
        shade: 0,
        area: ['1120px', '600px'],
        maxmin: true,
        zIndex: this.$layer.zIndex,
        title: stationInfo.stationName
      })

====================================
组件里面使用props:{data: String}接收

**Comment by zuoyanart** [comment]
fixed
