### ISSUE TITLE
弹窗移动的问题

### ISSUE THREAD

**Issue by cuitwangshicheng** [zuoyanart/vue-layer#39]
您好，我在使用的过程中发现，拖动弹出框iframe，一直往上拖动，然后松开就没法再去拖动了。看来源码，就是计算top的时候使用的clientY，不知使用文档的高度和宽度能否解决这个问题

**Comment by zuoyanart** [comment]
添加了上下左右边界的判断， 如果release新版本，更新版本即可

**Comment by cuitwangshicheng** [comment]
发布更新了哇？

**Comment by zuoyanart** [comment]
还有些东西正在开发，新版本你提交的bug，已经修复了，等完全改完会发布

**Comment by cuitwangshicheng** [comment]
好的，辛苦

**Comment by zuoyanart** [comment]
真的谢谢支持
