### ISSUE TITLE
无法找到模块“vue-layer”的声明文件，请问这是什么情况？

### ISSUE THREAD

**Issue by shibazijun** [zuoyanart/vue-layer#40]
无法找到模块“vue-layer”的声明文件。“d:/mode2/node_modules/_vue-layer@0.9.10@vue-layer/dist/vue-layer.js”隐式拥有 "any" 类型。
  Try `npm install @types/vue-layer` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-layer';`ts(7016)
module "d:/mode2/node_modules/_vue-layer@0.9.10@vue-layer/dist/vue-layer"

**Comment by zuoyanart** [comment]
目前还没有添加对ts的支持
