### ISSUE TITLE
layerid

### ISSUE THREAD

**Issue by liushuidylin** [zuoyanart/vue-layer#41]
// data参数可认为是componentName的props，同时 该方法会自动添加一个key为layerid的值， 该值为创建层的id， 可以直接用来关闭该层

我在弹出层怎么调用这个id呢，谢谢。 

我尝试用 props.id 、在props里面传入id、都获取不到这个id值。
现在只能通过`  this.$layer.closeAll()`  全部关闭

**Comment by cuitwangshicheng** [comment]
可以把id放到一个公共的空间，例如sessionStorage或者vuex中，绑定一个key值，自己维护这个key-value的数组对象，然后需要关闭的时候找到这个key的value来关闭

**Comment by liushuidylin** [comment]
非常感谢您的回答，已解决该问题。

**Comment by zuoyanart** [comment]
key的名称是layerid，
```js
{
 layerid: "id"
}
```
