### ISSUE TITLE
创建的时候必须传入vue 实例吗？

### ISSUE THREAD

**Issue by wangrenjie1** [zuoyanart/vue-layer#44]
使用问题：
我在使用axios时候  想通过 拦截response  统一处理 弹出的 返回信息   
但是在这个在 封装request.js  无法把vue  实例引过来，
怎样做 可以像  element-ui 一样  直接  import {message,MessageBox} from "element-ui";
这样 模块化的 引来用吗？

**Comment by zuoyanart** [comment]
现在还不行，需要通过vue对象，向页面注入元素，所以必须传入vue对象。你可以封装全局ajax的时候传入vue就可以了，我的工具类就是这样构建的
