### ISSUE TITLE
请问有没有loading的api？

### ISSUE THREAD

**Issue by vanoneang** [zuoyanart/vue-layer#49]
## 需求

请求api过程中，需要一个loading状态

## 说明

类似小程序的“加载中”

**Comment by zuoyanart** [comment]
暂时还不支持自定义，你可以在这提个需求

**Comment by vanoneang** [comment]
## 效果
![image](https://user-images.githubusercontent.com/29253688/56861685-c7a5e780-69d5-11e9-8612-5c005f88b502.png)

## 说明

类型上图这种，可以提供一个api控制显示隐藏，文字可自定义

**Comment by lingchong** [comment]
+1,希望提供下loading的状态api...

**Comment by zuoyanart** [comment]
详细描述下您的需求呢

**Comment by lingchong** [comment]
你好，我正在开发一个视频网站，弹窗部分使用了楼主开源的vue-layer，通过layer的iframe嵌入网页，希望在载入网页的过程中，能够提供加载的动画。以改善用户体验。 另外，楼主大佬，介意加个微信吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"左盐"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午2:13
收件人:&nbsp;"zuoyanart/vue-layer"<vue-layer@noreply.github.com&gt;;
抄送:&nbsp;"圣诞树"<2713318799@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zuoyanart/vue-layer] 请问有没有loading的api？ (#49)




详细描述下您的需求呢

**Comment by zuoyanart** [comment]
和三楼的那个例子类似吗？

**Comment by lingchong** [comment]
不一样诶...三楼是希望自定义loading的提示和控制loading状态的开关，我是希望this.$layer.iframe提供载入动画效果

**Comment by zuoyanart** [comment]
你的iframe里放的不是组件是一个url的地址？按说组件化开发，系统内的应用是不会出现iframe标签的。iframe和父窗的通信api也没有提供。可以再仔细描述下你的场景吗

**Comment by lingchong** [comment]
iframe弹框是被包裹在一个组件，通过layer的data属性传入url进去 ，希望url载入的时候，有加载的动画

**Comment by zuoyanart** [comment]
好的，我考虑下怎么做 @lingchong

**Comment by lingchong** [comment]
感谢楼主！

**Comment by zuoyanart** [comment]
我仔细考虑了你的需求，这个效果可能需要经常的定制，如果加入到layer有可能得不偿失，所以需求暂时先放这 @lingchong
