### ISSUE TITLE
tips方法获取定位的方法有点问题

### ISSUE THREAD

**Issue by PeggyWeb** [zuoyanart/vue-layer#53]
tips方法里getBoundingClientRect获取的定位会出现偏差

**Comment by zuoyanart** [comment]
我查查。另外：tips方法有废弃的打算，这个方法最好还是用vue 组件来实现。

**Comment by PeggyWeb** [comment]
tips挺好用的呀，为什么废弃？可以这样解决 document.querySelector('.operation input').getBoundingClientRect().top + document.documentElement.scrollTop

**Comment by zuoyanart** [comment]
fixed，稍后会发布新版本
