### ISSUE TITLE
layer.open type为1 时，样式丢失问题

### ISSUE THREAD

**Issue by wangminghuan** [zuoyanart/vue-layer#58]
### 执行以下代码：
    
               this.$layer.open({
                  type:"1",
                  title: '请扫码支付',
                  content: "<div class="payment-info">支付金额0元，实际到账0元</div>",
                  area: '340px',
                  icon: -1,
                  time: 0,
                  shade: true,//是否显示遮罩
                  shadeClose: true,//点击遮罩是否关闭
                })
     
### 最终渲染出来的dom结构为:

      <div class="notify">
          <div class="notify-mask"></div>
          <div id="notification_1562843883775_0_alert" class="notify-main notify-alert">
            <h2 class="title">请扫码支付</h2>
            <div class="notify-content">
                 <div class="payment-info">支付金额0元，实际到账0元</div>
           </div>
          </div>
      </div>

无法匹配到对应css样式

**Comment by wangminghuan** [comment]
vue-layer@^1.0.0:

**Comment by zuoyanart** [comment]
请尽量不要使用open方法，或者不要按照jQuery版的open方法使用，这不是jQuery的翻版
