### ISSUE TITLE
打包后IE9下报错

### ISSUE THREAD

**Issue by xinnianyoulin** [zuoyanart/vue-layer#6]
![image](https://user-images.githubusercontent.com/32128165/36961502-a561474e-2086-11e8-8eba-83d6277ecdb8.png)
![image](https://user-images.githubusercontent.com/32128165/36961520-bc6f93a0-2086-11e8-8194-8fab69cadd90.png)
IE9+下关闭操作弹窗后报错

**Comment by zuoyanart** [comment]
remove()方法，IE系全系未实现。 已经修复，更新至最新版即可

**Comment by xinnianyoulin** [comment]
已经用上啦~

**Comment by zuoyanart** [comment]
感觉好用的话，就star一下
