### ISSUE TITLE
有个问题。

### ISSUE THREAD

**Issue by 1973635434** [zuoyanart/vue-layer#62]
现在在弹框里面进行操作好像会导致 字体模糊一下（所有字体），我没找到是什么问题导致的

**Comment by zuoyanart** [comment]
是那个弹框？

**Comment by 1973635434** [comment]
layer.iframe   修改单选框 或者下拉框的时候 表单里面的字会模糊一下

**Comment by zuoyanart** [comment]
应该是transform导致的问题，我想想办法
