### ISSUE TITLE
关于vue-layer的一些建议

### ISSUE THREAD

**Issue by xinnianyoulin** [zuoyanart/vue-layer#7]
首先，现在正在做的这个项目需求是要有多个弹窗同时打开的。由于遮罩层没法用属性去除，所以覆盖了原来的最外层容器宽度样式(设为0)，遮罩层去了，但是因为原来的move事件是加在最外层容器上的，所以引发了 拖动稍快些，就会丢失窗体的问题。而且因为宽度没了，导致用到的loading没有加载层，容易误操作页面元素等。虽然现在外部重新写了move事件，实现了功能，但是这对性能并不是很友好。所以我觉得是否可以修改成弹窗最外层容器的宽度应该是和弹窗本身大小相等的，遮罩层为窗口大小，可以通过options控制，当然这里似乎还需要关闭按钮了，否则没了遮罩层还关闭不了，然后movestart后的move事件加在document上。

**Comment by zuoyanart** [comment]
好的，多开的情况我研究研究。谢谢

**Comment by xinnianyoulin** [comment]
Thanks

**Comment by zuoyanart** [comment]
请试用0.9.3版本
