### ISSUE TITLE
iframe层级问题

### ISSUE THREAD

**Issue by loatod** [zuoyanart/vue-layer#70]
你好，我想请问一下，我在layout内部的视图中使用iframe层的情况下，iframe最大化的时候可以不遮挡住layout的顶部菜单和tabs选项卡吗？在dom中可以看到layer的div是和app平级的，但我需要它是在tab-content内部，这一点可以通过设置parent做到吗？

**Comment by zuoyanart** [comment]
不好意思，暂时实现不了，我会考虑这个事情
