### ISSUE TITLE
怎么添加关闭回调函数？并可以在回调函数中控制是否关闭弹框？

### ISSUE THREAD

**Issue by gujunwuxichina** [zuoyanart/vue-layer#73]

**Comment by zuoyanart** [comment]
用的是那个方法? 具体描述下您的流程呢

**Comment by gujunwuxichina** [comment]
> 用的是那个方法? 具体描述下您的流程呢

用户打开编辑页面，修改了些数据，此时关闭弹框时，我想给个提示告诉用户编辑后的数据还未保存是否确定退出编辑，点确定则退出关闭弹框，取消则不关闭弹框

**Comment by zuoyanart** [comment]
iframe组件中

```js

export default {
  data() {
    return {
      form: {
      }
    };
  },
  props: {
    layerid: {
      type: String,
      default: ""
    },
    lydata: {
      type: Object,
      default: () => {
        return {};
      }
    }
  },
  methods: {
    onSubmit() {
      this.$layer.alert("提交成功", (lyid) => {
       this.$layer.close(lyid);//关闭alert
        this.$layer.close(this.layerid);//关闭iframe
      });
    }
  }
};
```

**Comment by gujunwuxichina** [comment]
> iframe组件中
> 
> ```js
> export default {
>   data() {
>     return {
>       form: {
>       }
>     };
>   },
>   props: {
>     layerid: {
>       type: String,
>       default: ""
>     },
>     lydata: {
>       type: Object,
>       default: () => {
>         return {};
>       }
>     }
>   },
>   methods: {
>     onSubmit() {
>       this.$layer.alert("提交成功", (lyid) => {
>        this.$layer.close(lyid);//关闭alert
>         this.$layer.close(this.layerid);//关闭iframe
>       });
>     }
>   }
> };
> ```

我想要那种点击X或遮罩关闭时也能进行统一拦截的回调

**Comment by zuoyanart** [comment]
```js
this.$layer.iframe({
  content: {
    content: formComp,
    parent: this,
    data: { iframeData: this.iframeData }
  },
  area: ['900px', '600px'],
  title: '这是一个标题',
  maxmin: true,
  shade: false,
  shadeClose: false,
  cancel: (layerid) => { //关闭弹窗事件
  this.$layer.alert("提交成功", (lyid) => {
       this.$layer.close(lyid);//关闭alert
        this.$layer.close(layerid);//关闭iframe
      });
  }
});
```
