### ISSUE TITLE
msg模块

### ISSUE THREAD

**Issue by chenmingyu0903** [zuoyanart/vue-layer#77]
layer.msg('你确定你很帅么？', {
  time: 0 //不自动关闭
  ,btn: ['必须啊', '丑到爆']
  ,yes: function(index){
    layer.close(index);
    layer.msg('雅蠛蝶 O.o', {
      icon: 6
      ,btn: ['嗷','嗷','嗷']
    });
  }
});
怎么达到这种效果，求问

**Comment by zuoyanart** [comment]
还是请用alert
