### ISSUE TITLE
事件捕获的疑问

### ISSUE THREAD

**Issue by cuitwangshicheng** [zuoyanart/vue-layer#78]
请问，如果iframe开启了minmax，如何捕获窗口的变化事件？
以及，在窗口内如何关闭自身？

**Comment by cuitwangshicheng** [comment]
现在知道怎么在弹窗内关闭自身了，但是关闭自身不会触发cancel事件，这个怎么处理呢？

**Comment by zuoyanart** [comment]
我想想要不要自动关联cancel事件

**Comment by zuoyanart** [comment]
关闭自身不一定是取消事件，还个还是需要你自己来组织逻辑
