### ISSUE TITLE
关闭iframe后会出现，遮罩层未关闭的问题

### ISSUE THREAD

**Issue by chezrb** [zuoyanart/vue-layer#83]
原因找到了，layer.js
![image](https://user-images.githubusercontent.com/23548034/74031588-e2899b80-49ec-11ea-9362-ba4de621a41c.png)
这两个地方都会有问题，key与self.instancesVue[key].main都会出undefined的情况，我看了示例没有这个问题，可能是我这把引入的框架太杂了

**Comment by mcck** [comment]
我也出现了这个文件，所有弹窗关闭的时候，会出现 Cannot read property 'shade' of undefined 
遮罩层未关闭

**Comment by zuoyanart** [comment]
我再来测试测试看看

**Comment by chezrb** [comment]
这个不是插件本身的问题，是引入第三方插件造成的

**Comment by zuoyanart** [comment]
好的

**Comment by jrlgit** [comment]
最小化iframe 遮罩层不能关闭

**Comment by jrlgit** [comment]
iframe最小化 遮罩层无法关闭
