### ISSUE TITLE
layer.msg 写入回调方法后，弹出层不能关闭，必须手动关闭

### ISSUE THREAD

**Issue by ahtcbweb** [zuoyanart/vue-layer#87]
this.$layer.msg('我可以自动关闭', (layerId) => {
      console.log('我现在不能自动关闭了:' + layerId)
})

不写回调方法可以自动关闭，写上以后，不能自动关闭 ！

**Comment by zuoyanart** [comment]
是的，就是这样设计的， 因为我不知道你的回调会执行什么东西
